-- This file has been generated by /usr/bin/notion. Do not edit.
return {
    [0] = {
        ["type"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["hidden"] = true,
                ["initial_outputs"] = {
                },
                ["geom"] = {
                    ["x"] = 0,
                    ["w"] = 3840,
                    ["h"] = 1080,
                    ["y"] = 0,
                },
                ["level"] = 0,
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["geom"] = {
                            ["x"] = 0,
                            ["w"] = 3840,
                            ["h"] = 1080,
                            ["y"] = 0,
                        },
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["type"] = "WTiling",
                        ["sizepolicy"] = "full",
                        ["split_tree"] = {
                            ["brs"] = 1920,
                            ["dir"] = "horizontal",
                            ["tls"] = 1920,
                            ["br"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["type"] = "WFrame",
                                    ["mode"] = 1,
                                    ["managed"] = {
                                        [1] = {
                                            ["geom"] = {
                                                ["x"] = 3,
                                                ["w"] = 1914,
                                                ["h"] = 1056,
                                                ["y"] = 21,
                                            },
                                            ["switchto"] = true,
                                            ["level"] = 0,
                                            ["type"] = "WGroupCW",
                                            ["sizepolicy"] = "full",
                                            ["managed"] = {
                                                [1] = {
                                                    ["checkcode"] = 2,
                                                    ["bottom"] = true,
                                                    ["geom"] = {
                                                        ["x"] = 1,
                                                        ["w"] = 1912,
                                                        ["h"] = 1050,
                                                        ["y"] = 3,
                                                    },
                                                    ["type"] = "WClientWin",
                                                    ["sizepolicy"] = "full",
                                                    ["level"] = 1,
                                                    ["windowid"] = 23068681,
                                                },
                                            },
                                            ["name"] = "WGroupCW<8>",
                                        },
                                    },
                                    ["name"] = "Tiling Frame<1>",
                                },
                            },
                            ["type"] = "WSplitSplit",
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["type"] = "WFrame",
                                    ["mode"] = 1,
                                    ["managed"] = {
                                        [1] = {
                                            ["geom"] = {
                                                ["x"] = 3,
                                                ["w"] = 1914,
                                                ["h"] = 1056,
                                                ["y"] = 21,
                                            },
                                            ["switchto"] = true,
                                            ["level"] = 0,
                                            ["type"] = "WGroupCW",
                                            ["sizepolicy"] = "full",
                                            ["managed"] = {
                                                [1] = {
                                                    ["checkcode"] = 1,
                                                    ["bottom"] = true,
                                                    ["geom"] = {
                                                        ["x"] = 1,
                                                        ["w"] = 1912,
                                                        ["h"] = 1050,
                                                        ["y"] = 3,
                                                    },
                                                    ["type"] = "WClientWin",
                                                    ["sizepolicy"] = "full",
                                                    ["level"] = 1,
                                                    ["windowid"] = 20971529,
                                                },
                                            },
                                            ["name"] = "WGroupCW<7>",
                                        },
                                    },
                                    ["name"] = "Tiling Frame<4>",
                                },
                            },
                        },
                        ["name"] = "WTiling",
                    },
                },
                ["name"] = "test123",
            },
            [2] = {
                ["geom"] = {
                    ["x"] = 0,
                    ["w"] = 3840,
                    ["h"] = 1080,
                    ["y"] = 0,
                },
                ["initial_outputs"] = {
                },
                ["switchto"] = true,
                ["level"] = 0,
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["geom"] = {
                            ["x"] = 0,
                            ["w"] = 3840,
                            ["h"] = 1080,
                            ["y"] = 0,
                        },
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["type"] = "WTiling",
                        ["sizepolicy"] = "full",
                        ["split_tree"] = {
                            ["brs"] = 1920,
                            ["dir"] = "horizontal",
                            ["tls"] = 1920,
                            ["br"] = {
                                ["brs"] = 960,
                                ["dir"] = "horizontal",
                                ["tls"] = 960,
                                ["br"] = {
                                    ["type"] = "WSplitRegion",
                                    ["regparams"] = {
                                        ["type"] = "WFrame",
                                        ["mode"] = 1,
                                        ["managed"] = {
                                            [1] = {
                                                ["geom"] = {
                                                    ["x"] = 3,
                                                    ["w"] = 954,
                                                    ["h"] = 1056,
                                                    ["y"] = 21,
                                                },
                                                ["hidden"] = true,
                                                ["level"] = 0,
                                                ["type"] = "WGroupCW",
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["checkcode"] = 9,
                                                        ["bottom"] = true,
                                                        ["geom"] = {
                                                            ["x"] = 1,
                                                            ["w"] = 953,
                                                            ["h"] = 1050,
                                                            ["y"] = 3,
                                                        },
                                                        ["type"] = "WClientWin",
                                                        ["sizepolicy"] = "full",
                                                        ["level"] = 1,
                                                        ["windowid"] = 33554441,
                                                    },
                                                },
                                                ["name"] = "WGroupCW<6>",
                                            },
                                            [2] = {
                                                ["geom"] = {
                                                    ["x"] = 3,
                                                    ["w"] = 954,
                                                    ["h"] = 1056,
                                                    ["y"] = 21,
                                                },
                                                ["switchto"] = true,
                                                ["level"] = 0,
                                                ["type"] = "WGroupCW",
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["checkcode"] = 10,
                                                        ["bottom"] = true,
                                                        ["geom"] = {
                                                            ["x"] = 1,
                                                            ["w"] = 953,
                                                            ["h"] = 1050,
                                                            ["y"] = 3,
                                                        },
                                                        ["type"] = "WClientWin",
                                                        ["sizepolicy"] = "full",
                                                        ["level"] = 1,
                                                        ["windowid"] = 31457289,
                                                    },
                                                },
                                                ["name"] = "WGroupCW<4>",
                                            },
                                        },
                                        ["name"] = "Tiling Frame<3>",
                                    },
                                },
                                ["type"] = "WSplitSplit",
                                ["tl"] = {
                                    ["type"] = "WSplitRegion",
                                    ["regparams"] = {
                                        ["type"] = "WFrame",
                                        ["mode"] = 1,
                                        ["managed"] = {
                                            [1] = {
                                                ["geom"] = {
                                                    ["x"] = 3,
                                                    ["w"] = 954,
                                                    ["h"] = 1056,
                                                    ["y"] = 21,
                                                },
                                                ["switchto"] = true,
                                                ["level"] = 0,
                                                ["type"] = "WGroupCW",
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["checkcode"] = 8,
                                                        ["bottom"] = true,
                                                        ["geom"] = {
                                                            ["x"] = 1,
                                                            ["w"] = 953,
                                                            ["h"] = 1050,
                                                            ["y"] = 3,
                                                        },
                                                        ["type"] = "WClientWin",
                                                        ["sizepolicy"] = "full",
                                                        ["level"] = 1,
                                                        ["windowid"] = 12582921,
                                                    },
                                                },
                                                ["name"] = "WGroupCW<1>",
                                            },
                                        },
                                        ["name"] = "Tiling Frame",
                                    },
                                },
                            },
                            ["type"] = "WSplitSplit",
                            ["tl"] = {
                                ["brs"] = 328,
                                ["dir"] = "horizontal",
                                ["tls"] = 1592,
                                ["br"] = {
                                    ["type"] = "WSplitRegion",
                                    ["regparams"] = {
                                        ["type"] = "WFrame",
                                        ["mode"] = 1,
                                        ["managed"] = {
                                            [1] = {
                                                ["geom"] = {
                                                    ["x"] = 3,
                                                    ["w"] = 322,
                                                    ["h"] = 1056,
                                                    ["y"] = 21,
                                                },
                                                ["switchto"] = true,
                                                ["level"] = 0,
                                                ["type"] = "WGroupCW",
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["checkcode"] = 7,
                                                        ["bottom"] = true,
                                                        ["geom"] = {
                                                            ["x"] = 0,
                                                            ["w"] = 322,
                                                            ["h"] = 1056,
                                                            ["y"] = 0,
                                                        },
                                                        ["type"] = "WClientWin",
                                                        ["sizepolicy"] = "full",
                                                        ["level"] = 1,
                                                        ["windowid"] = 14763378,
                                                    },
                                                },
                                                ["name"] = "WGroupCW<9>",
                                            },
                                        },
                                        ["name"] = "Tiling Frame<5>",
                                    },
                                },
                                ["type"] = "WSplitSplit",
                                ["tl"] = {
                                    ["type"] = "WSplitRegion",
                                    ["regparams"] = {
                                        ["type"] = "WFrame",
                                        ["mode"] = 1,
                                        ["managed"] = {
                                            [1] = {
                                                ["geom"] = {
                                                    ["x"] = 3,
                                                    ["w"] = 1586,
                                                    ["h"] = 1056,
                                                    ["y"] = 21,
                                                },
                                                ["hidden"] = true,
                                                ["level"] = 0,
                                                ["type"] = "WGroupCW",
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["checkcode"] = 3,
                                                        ["bottom"] = true,
                                                        ["geom"] = {
                                                            ["x"] = 0,
                                                            ["w"] = 1586,
                                                            ["h"] = 1050,
                                                            ["y"] = 3,
                                                        },
                                                        ["type"] = "WClientWin",
                                                        ["sizepolicy"] = "full",
                                                        ["level"] = 1,
                                                        ["windowid"] = 18874370,
                                                    },
                                                },
                                                ["name"] = "WGroupCW<5>",
                                            },
                                            [2] = {
                                                ["geom"] = {
                                                    ["x"] = 3,
                                                    ["w"] = 1586,
                                                    ["h"] = 1056,
                                                    ["y"] = 21,
                                                },
                                                ["switchto"] = true,
                                                ["level"] = 0,
                                                ["type"] = "WGroupCW",
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["checkcode"] = 4,
                                                        ["bottom"] = true,
                                                        ["geom"] = {
                                                            ["x"] = 0,
                                                            ["w"] = 1586,
                                                            ["h"] = 1045,
                                                            ["y"] = 6,
                                                        },
                                                        ["type"] = "WClientWin",
                                                        ["sizepolicy"] = "full",
                                                        ["level"] = 1,
                                                        ["windowid"] = 14680235,
                                                    },
                                                },
                                                ["name"] = "WGroupCW",
                                            },
                                            [3] = {
                                                ["geom"] = {
                                                    ["x"] = 3,
                                                    ["w"] = 1586,
                                                    ["h"] = 1056,
                                                    ["y"] = 21,
                                                },
                                                ["hidden"] = true,
                                                ["level"] = 0,
                                                ["type"] = "WGroupCW",
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["checkcode"] = 5,
                                                        ["bottom"] = true,
                                                        ["geom"] = {
                                                            ["x"] = 2,
                                                            ["w"] = 1583,
                                                            ["h"] = 1050,
                                                            ["y"] = 3,
                                                        },
                                                        ["type"] = "WClientWin",
                                                        ["sizepolicy"] = "full",
                                                        ["level"] = 1,
                                                        ["windowid"] = 25165833,
                                                    },
                                                },
                                                ["name"] = "WGroupCW<3>",
                                            },
                                            [4] = {
                                                ["geom"] = {
                                                    ["x"] = 3,
                                                    ["w"] = 1586,
                                                    ["h"] = 1056,
                                                    ["y"] = 21,
                                                },
                                                ["hidden"] = true,
                                                ["level"] = 0,
                                                ["type"] = "WGroupCW",
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["checkcode"] = 6,
                                                        ["bottom"] = true,
                                                        ["geom"] = {
                                                            ["x"] = 0,
                                                            ["w"] = 1586,
                                                            ["h"] = 1056,
                                                            ["y"] = 0,
                                                        },
                                                        ["type"] = "WClientWin",
                                                        ["sizepolicy"] = "full",
                                                        ["level"] = 1,
                                                        ["windowid"] = 29361094,
                                                    },
                                                },
                                                ["name"] = "WGroupCW<2>",
                                            },
                                        },
                                        ["name"] = "Tiling Frame<2>",
                                    },
                                },
                            },
                        },
                        ["name"] = "WTiling<1>",
                    },
                },
                ["name"] = "windows",
            },
            [3] = {
                ["geom"] = {
                    ["x"] = 0,
                    ["w"] = 3840,
                    ["h"] = 1080,
                    ["y"] = 0,
                },
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["geom"] = {
                            ["x"] = 1600,
                            ["w"] = 640,
                            ["h"] = 480,
                            ["y"] = 300,
                        },
                        ["mode"] = 0,
                        ["level"] = 1025,
                        ["type"] = "WFrame",
                        ["sizepolicy"] = "free_glue",
                        ["managed"] = {
                        },
                        ["name"] = "*scratchpad*",
                    },
                },
                ["unnumbered"] = true,
                ["initial_outputs"] = {
                },
                ["pseudomodal"] = true,
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["level"] = 1,
                ["name"] = "*scratchws*",
            },
        },
        ["name"] = "WScreen",
    },
}

